### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RBKweb-ext#48]
[larsa@kindred] ~/Code/rbk/RBKweb-ext (master)$ git pull
Already up to date.

[larsa@kindred] ~/Code/rbk/RBKweb-ext (master)$ git log -1
commit b425c5f9e2c2398bb656f0b29cd21a22302087d2 (HEAD -> master, origin/master, origin/HEAD)
Author: Rune Jacobsen <havremunken@gmail.com>
Date:   Thu Nov 22 20:22:59 2018 +0100

    Have content script use module loader to execute

[larsa@kindred] ~/Code/rbk/RBKweb-ext (master)$ npm install
audited 5370 packages in 4.099s
found 0 vulnerabilities

[larsa@kindred] ~/Code/rbk/RBKweb-ext (master)$ npm  run build

> rbkweb-chrome-ext@0.0.0 build /Users/larsa/Code/rbk/RBKweb-ext
> webpack --config webpack/webpack.prod.js

Hash: f9363427cd6d69edf2dc
Version: webpack 4.17.3
Time: 1882ms
Built at: 11/22/2018 11:45:20 PM
 5 assets
Entrypoint popup = vendor.js popup.js
Entrypoint options = vendor.js options.js
Entrypoint background = background.js
Entrypoint content_script = content_script.js
[1] ./src/popup.ts 927 bytes {1} [built]
[3] (webpack)/buildin/module.js 497 bytes {0} [built]
[4] ./src/options.ts 1.09 KiB {2} [built]
[5] ./src/background.ts 625 bytes {3} [built]
[6] ./src/content_script.ts 486 bytes {4} [built] [failed] [2 errors]
    + 2 hidden modules

ERROR in ./src/content_script.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/larsa/Code/rbk/RBKweb-ext/src/content_script.ts.
    at makeSourceMapAndFinish (/Users/larsa/Code/rbk/RBKweb-ext/node_modules/ts-loader/dist/index.js:78:15)
    at successLoader (/Users/larsa/Code/rbk/RBKweb-ext/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/larsa/Code/rbk/RBKweb-ext/node_modules/ts-loader/dist/index.js:22:12)

ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/content_script.ts
./src/content_script.ts
[tsl] ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/content_script.ts(2,33)
      TS2307: Cannot find module './ExtensionModules/extensionmodule'.

ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/EM_Brukertips.ts
[tsl] ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/EM_Brukertips.ts(1,33)
      TS2307: Cannot find module './extensionmodule'.

ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/EM_Brukertips.ts
[tsl] ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/EM_Brukertips.ts(2,31)
      TS2307: Cannot find module '../Configuration/configoptions'.

ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/EM_Brukertips.ts
[tsl] ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/EM_Brukertips.ts(3,29)
      TS2307: Cannot find module '../Configuration/settingtype'.

ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/ExtensionModuleLoader.ts
[tsl] ERROR in /Users/larsa/Code/rbk/RBKweb-ext/src/ExtensionModules/ExtensionModuleLoader.ts(1,33)
      TS2307: Cannot find module './extensionmodule'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rbkweb-chrome-ext@0.0.0 build: `webpack --config webpack/webpack.prod.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the rbkweb-chrome-ext@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/larsa/.npm/_logs/2018-11-22T22_45_20_189Z-debug.log

**Comment by larsjaas** [comment]
filesystem case sensitivity killed the cat
